version: '2'
services: 
  postgres: 
    image:  ${DockerRegistryServer}/${JOB_NAME}_postgres:${BUILD_NUMBER}
    hostname: mypostgres
    
# Service name
  tomcat1: 
    image:  ${DockerRegistryServer}/${JOB_NAME}_tomcat:${BUILD_NUMBER}
    links: 
      - postgres
    hostname: web1
    environment:
      - JDBC_URL="jdbc:postgresql://postgres:5432/UserDB"

  tomcat2: 
    image:  ${DockerRegistryServer}/${JOB_NAME}_tomcat:${BUILD_NUMBER}
    links: 
      - postgres
    hostname: web2
    environment:
      - JDBC_URL="jdbc:postgresql://postgres:5432/UserDB"

  nginx: 
    image:  ${DockerRegistryServer}/${JOB_NAME}_nginx:${BUILD_NUMBER}
    ports: 
        - "80"
    links: 
      - tomcat1
      - tomcat2
    environment:
      - WEB_SERVERS=tomcat1,tomcat2

